### ISSUE TITLE
onReady: Cannot read property 'webContents' of null

### ISSUE THREAD

**Issue by L3V147H4N** [azain/electron-window-manager#8] opened 2016-07-22 20:29 UTC
I'm getting this error when setting the onReady callback

![image](https://cloud.githubusercontent.com/assets/5846479/17070361/d1b0ef24-5031-11e6-9587-69a54a894948.png)

```
app.on('ready', function(){
  windowManager.init();
  // Create Main Window Instance
  var mainWindow = windowManager.createNew('main', 'Main Window', app.getAppPath() + '\\out\\main-window.html', false, {
    width: 800,
    height: 600
  }, true);
  // Register on ready callback
  mainWindow.onReady(true, window => {
    console.log('main ready!');
  });
  // Open Main Window
  mainWindow.open();
});
```

**Comment by L3V147H4N** [comment] 2016-07-22 20:55
The createWindow method returns a Window instance with no methods

**Comment by shrimpwagon** [comment] 2016-10-12 15:37
@L3V147H4N Is this still an issue?

**Comment by L3V147H4N** [comment] 2016-10-17 12:41
sorry, I abstained from using this library, I will test it further more in the future

**Comment by shrimpwagon** [comment] 2016-10-17 12:51
@L3V147H4N @azain 
Please close this issue

**Closed** 2016-10-17 13:53 UTC

**Comment by asmsuechan** [comment] 2017-02-22 08:22
Hi, I hit this same problem. I left a comment how to fix it for someone who hits the same issue. You should remove `mainWindow.onReady` from your code. After removes it, the window works fine.

Presumably, the cause of this problem is [here](https://github.com/TamkeenLMS/electron-window-manager/blob/master/index.js#L330:L332). I assume `this.object` returns null. It's used by a definition of [onReady](https://github.com/TamkeenLMS/electron-window-manager/blob/master/index.js#L362:L370).
